id: A3CB6BC5E
title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
  Female Practice'
type: translation
pechas:
- I3C8E9405
- I9F83968D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:43:23.868027
  last_modified_at: 2023-01-04 11:43:23.868032
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  I3C8E9405/9114: '9222'
  I9F83968D/8050: '9222'
